TESTDIR ?= $(abspath ../test)
LOGDIR ?= $(abspath ../tmp)

TESTBENCHS = \
            SimDma.bsv \
            SimExtractRdmaHeaderPayload.bsv \
            SimGenRdmaReqResp.bsv \
            TestArbitration.bsv \
            TestController.bsv \
            TestDupReadAtomicCache.bsv \
            TestExtractAndPrependPipeOut.bsv \
            TestInputPktHandle.bsv \
            TestMetaData.bsv \
            TestPayloadConAndGen.bsv \
            TestQueuePair.bsv \
            TestReqGenSQ.bsv \
            TestReqHandleRQ.bsv \
            TestRespHandleSQ.bsv \
            TestRetryHandleSQ.bsv \
            TestSpecialFIFOF.bsv \
            TestTransportLayer.bsv \
            TestUtils.bsv \
            TestWorkCompGen.bsv \
            TestPayloadGen.bsv \
            TestSendQ.bsv \
            TestQPContext.bsv \
			TestRQ.bsv \
			TestTop.bsv

TestQPContext.bsv                       = mkTestQueryContxt 

TestPayloadGen.bsv               = mkTestAddrChunkSrv \
                                    mkTestDmaReadCntrlScatterGatherListCase \
                                    mkTestDmaReadCntrlNormalCase \
                                    mkTestDmaReadCntrlCancelCase \
                                    mkTestMergeNormalPayloadEachSGE \
                                    mkTestMergeSmallPayloadEachSGE \
                                    mkTestMergeNormalPayloadAllSGE \
                                    mkTestMergeSmallPayloadAllSGE \
                                    mkTestAdjustNormalPayloadSegmentCase \
                                    mkTestAdjustSmallPayloadSegmentCase \
                                    mkTestPayloadGenNormalCase \
                                    mkTestPayloadGenSmallCase \
                                    mkTestPayloadGenZeroCase

TestSendQ.bsv                    = mkTestSendQueueRawPktCase \
                                    mkTestSendQueueNormalCase \
                                    mkTestSendQueueNoPayloadCase \
                                    mkTestSendQueueZeroPayloadLenCase

all: $(TESTBENCHS)

%.bsv:
	$(foreach testcase, $($@), $(shell cd $(TESTDIR) && make simulate TESTFILE=$@ TOPMODULE=$(testcase) > $(LOGDIR)/$@-$(testcase).log 2>&1))

clean:
	rm -f $(LOGDIR)/*.log

.PHONY: all TESTBENCHS %.bsv clean
.DEFAULT_GOAL := all
