//
// Generated by Bluespec Compiler, version 2023.01 (build 52adafa5)
//
// On Mon Nov 20 11:42:43 CST 2023
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTB(CLK,
	    RST_N);
  input  CLK;
  input  RST_N;

  // register a_t
  reg a_t;
  wire a_t$D_IN, a_t$EN;

  // register a_t
  assign a_t$D_IN = 1'b0 ;
  assign a_t$EN = 1'b0 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (a_t$EN) a_t <= `BSV_ASSIGNMENT_DELAY a_t$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    a_t = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTB

